### ISSUE TITLE
Use Vale to enforce brand capitalization and other doc style guides

### ISSUE THREAD

**Issue by HonkingGoose** [semantic-release/semantic-release#2470]
## Intro

Your `CONTRIBUTING.md` guide states:

https://github.com/semantic-release/semantic-release/blob/587bb91c9a0a9f8eaab18c3ee4ef9f1cea9a8b48/CONTRIBUTING.md?plain=1#L114-L115

## Proposal

The capitalization of brand names can be enforced by the Vale linter.

I can help set up Vale for you, if you want.

## Todo list

To get this working you need to:

- [ ] Install Vale [^vale-repo]
- [ ] Setup "Vocab rules" [^vale-vocab]
- [ ] Setup any other Style guidelines that you want to follow/enforce
- [ ] Run Vale in a GitHub Action

## Example of custom vocabulary list

I've been working on a custom vocabulary list for the Renovate bot project, take a look.

<details><summary>Click me to see example vocabulary list</summary>

```txt
# This is the list of acceptable vocab for the Renovate project.

# By default all entries are case sensitive!
# Use (?i) to mark the entire pattern case insensitive.
# Use [Oo]bservability to accept both observability and Observability.

# Docs: https://docs.errata.ai/vale/vocab

[Aa]utodetect
[Aa]utomerge
[Aa]utomerging
[Cc]odeowners
[Cc]onfig
[Dd]atasource
[Ff]unction
[Mm]aintain
[yaml, YAML]
AdBlock
Ansible
Artifactory
breejs
Bundler
codecov
cron
Dependabot
Docker
Dockerfile
dotnet
ESLint
Gemfile
Gitea
GitHub
GitLab
Gitpod
Gradle
Habjan
hostname
HTTP
HTTPS
JavaScript
js
lockfile
mergeable
minimatch
MongoDB
monorepo
monorepos
MySQL
namespace
Nejc
nodenv
npm
npmrc
NuGet
Packagist
PHP
Pipenv
pnpm
rebase
rebasing
Renovate bot
repo
SemVer
TypeScript
URIs
URL
URLs
Vue
Webpack
```

</details>

[^vale-repo]: [`errata-ai/vale` repository](https://github.com/errata-ai/vale)
[^vale-vocab]: [Vale docs for Vocab](https://vale.sh/docs/topics/vocab/)

**Comment by gr2m** [comment]
I'm reluctant to add more tooling and potentially more friction to users/maintainers of @semantic-release, it's hard to maintain as is. It sounds like a great product/idea, but we try to remove complexity right now, not add more.

What is your own experience with vale? Can you share some insights about the friction it may cause?

**Comment by HonkingGoose** [comment]
> I'm reluctant to add more tooling and potentially more friction to users/maintainers of @semantic-release, it's hard to maintain as is. It sounds like a great product/idea, but we try to remove complexity right now, not add more.

Yeah, I can understand that. There's a balance between helping new contributors do the right thing the first time round, and maintainer hassle.

I just read the contributing docs, and saw that some of these documentation rules can be enforced by Vale. That way people can just commit, and let the linter tell them if it's right or not.

Those documentation typo fixes you just merged were all caught by the Vale linter. 😉 

> What is your own experience with vale? Can you share some insights about the friction it may cause?

I'm still busy integrating Vale, plus some custom rules, for the `renovatebot/renovate` repository. So I can't tell how much friction it causes in the real world.

I expect that the hardest thing is to get started. You'll need a custom vocabulary for words like `GitHub`, `GitLab`, `GitHub Codespaces`, and so on. You can also set how "strict" Vale should be, and what "error level" Vale should report.

Once Vale is setup, these things will need maintenance:

- Manually add new words to the allow list
- Manually update to newer Vale versions
- Merge Vale GitHub Action runner updates from Renovate bot

**Comment by gr2m** [comment]
maybe let's leave this open for now and gather some experience with renovate, then revisit after you used it for a few months?
