### ISSUE TITLE
Roadmap 4.x@latest

### ISSUE THREAD

**Issue by boennemann** [semantic-release/semantic-release#52]
The 4.x rewrite is very stable in general, but I'd like to address a few more things before 4.x officially moves to `latest`.

- [x] 700ec9d4ca06d7a0c4b7bc153ff284eb71e75f5d Implement plugin pipelines, so it's possible to run multiple verifications easily, w/o any overhead.
- [x] Come up with a way to automatically do the right thing when a `next` release is done for the first time. Currently: [just an error](https://github.com/semantic-release/semantic-release/blob/next/src/lib/last-release.js#L18)
- [ ] ~~Implement #40 and #41~~
- [ ] ~~Make integration tests work and automatically executed on Travis~~
- [ ] ~~Develop some more plugins, more dogfooding before we lock the plugin api, also bigger ecosystem~~
- … ?

Feedback appreciated

@christophwitzko @gr2m

**Comment by gr2m** [comment]
I wonder if we could make `semantic-release-cli` smart enough to migrate semantic-release@3 setups?

**Comment by boennemann** [comment]
@gr2m Doing a quick github code search gives me the impression that that's not really worth the effort. The existing [migration guide](https://github.com/semantic-release/semantic-release/releases/tag/v4.0.0) is also pretty straight forward, I hope? :)

**Comment by gr2m** [comment]
> The existing migration guide is also pretty straight forward

It is :) It would have been just a bonus, nevermind then

**Comment by ariporad** [comment]
Did the integration tests ever start running on travis?

**Comment by boennemann** [comment]
@ariporad Unfortunately they didn't. Always some weird issue with getting CouchDB to start.

**Comment by boennemann** [comment]
I got more and more error reports, because people were installing the 3.x branch. I've now moved 4.2.1 over to `latest` earlier to get this problem out of the way.

I'll further develop on `next` and will cherry-pick features and fixes onto master, until I'm confident to release 5.x as latest.

**Comment by gr2m** [comment]
w00p congrats :tada:
